os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '10.15.3'
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
addons:
  sonarcloud:
    organization: 'c2v4-github' # the key of the org you chose at step #3
env:
  global:
    - NODE_VERSION=10.15.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - set -e
  - chmod +x gradlew
  - ./gradlew clean test integrationTest bootJar
  - python <(curl https://raw.githubusercontent.com/tomato-bot/tomato/master/tomato-lib/tomato_lib.py) build/test-results/*/TEST*.xml
  #- ./gradlew sonarqube -Dsonar.projectKey=c2v4_greenery -Dsonar.organization=c2v4-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH -x test
  - sonar-scanner
  - ./gradlew bootJar -Pprod -x test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew jibDockerBuild -Pprod ; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew jibDockerBuild -Pprod -Praspberry ; fi
  - if [ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; fi
  - if [ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" != "false" ]; then docker push c2v4/greenery ; fi
  - if [ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" != "false" ]; then docker push c2v4/greenery-raspberry ; fi
notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
