os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '10.15.3'
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
env:
  global:
    - NODE_VERSION=10.15.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - set -e
  - chmod +x gradlew
  - ./gradlew clean test integrationTest
  - python <(curl https://raw.githubusercontent.com/tomato-bot/tomato/master/tomato-lib/tomato_lib.py) build/test-results/*/TEST*.xml
  - ./gradlew sonarqube -Dsonar.projectKey=c2v4_greenery -Dsonar.organization=c2v4-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH
  - ./gradlew bootJar -Pprod -x test
  - test $TRAVIS_BRANCH = "master" && ./gradlew jibDockerBuild -Pprod
  - test $TRAVIS_BRANCH = "master" && ./gradlew jibDockerBuild -Pprod -Praspberry
  - test $TRAVIS_BRANCH = "master" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - test $TRAVIS_BRANCH = "master" && docker push c2v4/greenery
  - test $TRAVIS_BRANCH = "master" && docker push c2v4/greenery-raspberry
notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
